### ISSUE TITLE
Names Over head

### ISSUE THREAD

**Issue by dan2735** [ischmal/Photon#1]
Photon messes up the DarkRP name over head feature. Removing it fixes it.

**Comment by ischmal** [comment]
Do you have any specific instances or examples? I can't seem to recreate this in DarkRP or find anything code-wise where this could happen.

**Comment by ischmal** [comment]
Disregard, it has to do with rendering hooks and not network data -- changing gears and checking again

**Comment by ischmal** [comment]
Fix found and patch released. Thanks so much for letting me know.

http://steamcommunity.com/sharedfiles/filedetails/changelog/339648087
